version: "3.8"
services:
        tensorflow:
                build: .
                image: tensorflow:latest
                stdin_open: true # docker run -i
                tty: true        # docker run -t 
                ports:
                        - "8888:8888"
                volumes:
                        - "./:/projects/dlp"
